import { Item } from '../types';

// Sahityotsav 2026 — 170 official events
// Item codes are sequential within each category prefix (LP-001..LP-014, UP-001..UP-016, etc.)
// item_name_ml : now fully replaced with English display names
export const HANDBOOK_ITEMS: Item[] = [

  // ── Lower Primary (LP) — 14 items ──
  { id: 'item-lp-001', item_code: 'LP-001', item_name_ml: 'Madh Song',                      participation_type: 'individual', category_codes: ['LP'], duration_minutes: 5  },
  { id: 'item-lp-002', item_code: 'LP-002', item_name_ml: 'Speech',                         participation_type: 'individual', category_codes: ['LP'], duration_minutes: 5  },
  { id: 'item-lp-003', item_code: 'LP-003', item_name_ml: 'Quiz',                           participation_type: 'individual', category_codes: ['LP']                       },
  { id: 'item-lp-004', item_code: 'LP-004', item_name_ml: 'Story Narration',                participation_type: 'individual', category_codes: ['LP'], duration_minutes: 5  },
  { id: 'item-lp-005', item_code: 'LP-005', item_name_ml: 'Drawing – Pencil',               participation_type: 'individual', category_codes: ['LP'], duration_minutes: 60 },
  { id: 'item-lp-006', item_code: 'LP-006', item_name_ml: 'Drawing – Watercolour',          participation_type: 'individual', category_codes: ['LP'], duration_minutes: 60 },
  { id: 'item-lp-007', item_code: 'LP-007', item_name_ml: 'Language Game',                  participation_type: 'individual', category_codes: ['LP']                       },
  { id: 'item-lp-008', item_code: 'LP-008', item_name_ml: 'Reading – Malayalam',            participation_type: 'individual', category_codes: ['LP'], duration_minutes: 3  },
  { id: 'item-lp-009', item_code: 'LP-009', item_name_ml: 'Reading – Arabi-Malayalam',       participation_type: 'individual', category_codes: ['LP'], duration_minutes: 3  },
  { id: 'item-lp-010', item_code: 'LP-010', item_name_ml: 'Book Test',                      participation_type: 'individual', category_codes: ['LP'], duration_minutes: 15 },
  { id: 'item-lp-011', item_code: 'LP-011', item_name_ml: 'Drawing – Pencil (Girls)',        participation_type: 'individual', category_codes: ['LP']                       },
  { id: 'item-lp-012', item_code: 'LP-012', item_name_ml: 'Drawing – Watercolour (Girls)',   participation_type: 'individual', category_codes: ['LP']                       },
  { id: 'item-lp-013', item_code: 'LP-013', item_name_ml: 'Handwriting – Malayalam (Girls)', participation_type: 'individual', category_codes: ['LP']                       },
  { id: 'item-lp-014', item_code: 'LP-014', item_name_ml: 'Journal Art (Girls)',             participation_type: 'individual', category_codes: ['LP']                       },

  // ── Upper Primary (UP) — 16 items ──
  { id: 'item-up-001', item_code: 'UP-001', item_name_ml: 'Mappila Song',                   participation_type: 'individual', category_codes: ['UP'], duration_minutes: 5  },
  { id: 'item-up-002', item_code: 'UP-002', item_name_ml: 'Story Narration',                participation_type: 'individual', category_codes: ['UP'], duration_minutes: 5  },
  { id: 'item-up-003', item_code: 'UP-003', item_name_ml: 'Speech',                         participation_type: 'individual', category_codes: ['UP'], duration_minutes: 5  },
  { id: 'item-up-004', item_code: 'UP-004', item_name_ml: 'Mathematics Game',               participation_type: 'individual', category_codes: ['UP']                       },
  { id: 'item-up-005', item_code: 'UP-005', item_name_ml: 'Quiz',                           participation_type: 'individual', category_codes: ['UP']                       },
  { id: 'item-up-006', item_code: 'UP-006', item_name_ml: 'Drawing – Pencil',               participation_type: 'individual', category_codes: ['UP'], duration_minutes: 60 },
  { id: 'item-up-007', item_code: 'UP-007', item_name_ml: 'Drawing – Watercolour',          participation_type: 'individual', category_codes: ['UP'], duration_minutes: 60 },
  { id: 'item-up-008', item_code: 'UP-008', item_name_ml: 'Story Writing',                  participation_type: 'individual', category_codes: ['UP'], duration_minutes: 40 },
  { id: 'item-up-009', item_code: 'UP-009', item_name_ml: 'Book Test',                      participation_type: 'individual', category_codes: ['UP'], duration_minutes: 15 },
  { id: 'item-up-010', item_code: 'UP-010', item_name_ml: 'Spelling Bee',                   participation_type: 'individual', category_codes: ['UP']                       },
  { id: 'item-up-011', item_code: 'UP-011', item_name_ml: 'Sudoku',                         participation_type: 'individual', category_codes: ['UP']                       },
  { id: 'item-up-012', item_code: 'UP-012', item_name_ml: 'Drawing – Pencil (Girls)',        participation_type: 'individual', category_codes: ['UP']                       },
  { id: 'item-up-013', item_code: 'UP-013', item_name_ml: 'Drawing – Watercolour (Girls)',   participation_type: 'individual', category_codes: ['UP']                       },
  { id: 'item-up-014', item_code: 'UP-014', item_name_ml: 'Book Test (Girls)',               participation_type: 'individual', category_codes: ['UP']                       },
  { id: 'item-up-015', item_code: 'UP-015', item_name_ml: 'Story Writing (Girls)',           participation_type: 'individual', category_codes: ['UP']                       },
  { id: 'item-up-016', item_code: 'UP-016', item_name_ml: 'Origami (Girls)',                 participation_type: 'individual', category_codes: ['UP']                       },

  // ── High School (HS) — 23 items ──
  { id: 'item-hs-001', item_code: 'HS-001', item_name_ml: 'Speech – Malayalam',             participation_type: 'individual', category_codes: ['HS'], duration_minutes: 5  },
  { id: 'item-hs-002', item_code: 'HS-002', item_name_ml: 'Speech – English',               participation_type: 'individual', category_codes: ['HS'], duration_minutes: 5  },
  { id: 'item-hs-003', item_code: 'HS-003', item_name_ml: 'Mappila Song',                   participation_type: 'individual', category_codes: ['HS'], duration_minutes: 5  },
  { id: 'item-hs-004', item_code: 'HS-004', item_name_ml: 'Madh Song',                      participation_type: 'individual', category_codes: ['HS'], duration_minutes: 5  },
  { id: 'item-hs-005', item_code: 'HS-005', item_name_ml: 'Arabic Poem Recitation',         participation_type: 'individual', category_codes: ['HS'], duration_minutes: 5  },
  { id: 'item-hs-006', item_code: 'HS-006', item_name_ml: 'Poem Recitation – Malayalam',    participation_type: 'individual', category_codes: ['HS'], duration_minutes: 5  },
  { id: 'item-hs-007', item_code: 'HS-007', item_name_ml: 'Poem Recitation – Urdu',         participation_type: 'individual', category_codes: ['HS'], duration_minutes: 5  },
  { id: 'item-hs-008', item_code: 'HS-008', item_name_ml: 'Quiz',                           participation_type: 'individual', category_codes: ['HS']                       },
  { id: 'item-hs-009', item_code: 'HS-009', item_name_ml: 'Story Writing',                  participation_type: 'individual', category_codes: ['HS'], duration_minutes: 40 },
  { id: 'item-hs-010', item_code: 'HS-010', item_name_ml: 'Poetry Writing',                 participation_type: 'individual', category_codes: ['HS'], duration_minutes: 40 },
  { id: 'item-hs-011', item_code: 'HS-011', item_name_ml: 'Drawing – Pencil',               participation_type: 'individual', category_codes: ['HS'], duration_minutes: 60 },
  { id: 'item-hs-012', item_code: 'HS-012', item_name_ml: 'Drawing – Watercolour',          participation_type: 'individual', category_codes: ['HS'], duration_minutes: 60 },
  { id: 'item-hs-013', item_code: 'HS-013', item_name_ml: 'Book Test',                      participation_type: 'individual', category_codes: ['HS'], duration_minutes: 15 },
  { id: 'item-hs-014', item_code: 'HS-014', item_name_ml: 'Essay – Malayalam',              participation_type: 'individual', category_codes: ['HS'], duration_minutes: 30 },
  { id: 'item-hs-015', item_code: 'HS-015', item_name_ml: 'News Reading',                   participation_type: 'individual', category_codes: ['HS'], duration_minutes: 5  },
  { id: 'item-hs-016', item_code: 'HS-016', item_name_ml: 'Caption Writing',                participation_type: 'individual', category_codes: ['HS'], duration_minutes: 15 },
  { id: 'item-hs-017', item_code: 'HS-017', item_name_ml: 'Language Game – English',        participation_type: 'individual', category_codes: ['HS']                       },
  { id: 'item-hs-018', item_code: 'HS-018', item_name_ml: 'Embroidery (Girls)',              participation_type: 'individual', category_codes: ['HS']                       },
  { id: 'item-hs-019', item_code: 'HS-019', item_name_ml: 'Book Test (Girls)',               participation_type: 'individual', category_codes: ['HS']                       },
  { id: 'item-hs-020', item_code: 'HS-020', item_name_ml: 'Drawing – Pencil (Girls)',        participation_type: 'individual', category_codes: ['HS']                       },
  { id: 'item-hs-021', item_code: 'HS-021', item_name_ml: 'Drawing – Watercolour (Girls)',   participation_type: 'individual', category_codes: ['HS']                       },
  { id: 'item-hs-022', item_code: 'HS-022', item_name_ml: 'Story Writing (Girls)',           participation_type: 'individual', category_codes: ['HS']                       },
  { id: 'item-hs-023', item_code: 'HS-023', item_name_ml: 'Poetry Writing (Girls)',          participation_type: 'individual', category_codes: ['HS']                       },

  // ── Higher Secondary (HSS) — 20 items ──
  { id: 'item-hss-001', item_code: 'HSS-001', item_name_ml: 'Urdu Poem Recitation',          participation_type: 'individual', category_codes: ['HSS'], duration_minutes: 5  },
  { id: 'item-hss-002', item_code: 'HSS-002', item_name_ml: 'Mappila Song',                  participation_type: 'individual', category_codes: ['HSS'], duration_minutes: 5  },
  { id: 'item-hss-003', item_code: 'HSS-003', item_name_ml: 'Devotional Song',               participation_type: 'individual', category_codes: ['HSS'], duration_minutes: 5  },
  { id: 'item-hss-004', item_code: 'HSS-004', item_name_ml: 'Speech',                        participation_type: 'individual', category_codes: ['HSS'], duration_minutes: 5  },
  { id: 'item-hss-005', item_code: 'HSS-005', item_name_ml: 'Digital Painting',              participation_type: 'individual', category_codes: ['HSS'], duration_minutes: 60 },
  { id: 'item-hss-006', item_code: 'HSS-006', item_name_ml: 'Story Writing',                 participation_type: 'individual', category_codes: ['HSS'], duration_minutes: 40 },
  { id: 'item-hss-007', item_code: 'HSS-007', item_name_ml: 'Poetry Writing',                participation_type: 'individual', category_codes: ['HSS'], duration_minutes: 40 },
  { id: 'item-hss-008', item_code: 'HSS-008', item_name_ml: 'Essay – Malayalam',             participation_type: 'individual', category_codes: ['HSS'], duration_minutes: 30 },
  { id: 'item-hss-009', item_code: 'HSS-009', item_name_ml: 'Essay – English',               participation_type: 'individual', category_codes: ['HSS'], duration_minutes: 30 },
  { id: 'item-hss-010', item_code: 'HSS-010', item_name_ml: 'Quiz',                          participation_type: 'individual', category_codes: ['HSS']                       },
  { id: 'item-hss-011', item_code: 'HSS-011', item_name_ml: 'Drawing – Pencil',              participation_type: 'individual', category_codes: ['HSS'], duration_minutes: 60 },
  { id: 'item-hss-012', item_code: 'HSS-012', item_name_ml: 'Drawing – Watercolour',         participation_type: 'individual', category_codes: ['HSS'], duration_minutes: 60 },
  { id: 'item-hss-013', item_code: 'HSS-013', item_name_ml: 'Book Test',                     participation_type: 'individual', category_codes: ['HSS'], duration_minutes: 15 },
  { id: 'item-hss-014', item_code: 'HSS-014', item_name_ml: 'News Writing',                  participation_type: 'individual', category_codes: ['HSS'], duration_minutes: 20 },
  { id: 'item-hss-015', item_code: 'HSS-015', item_name_ml: 'Arabic Calligraphy',            participation_type: 'individual', category_codes: ['HSS'], duration_minutes: 60 },
  { id: 'item-hss-016', item_code: 'HSS-016', item_name_ml: 'Reel Making',                   participation_type: 'individual', category_codes: ['HSS']                       },
  { id: 'item-hss-017', item_code: 'HSS-017', item_name_ml: 'Arabic Calligraphy (Girls)',     participation_type: 'individual', category_codes: ['HSS']                       },
  { id: 'item-hss-018', item_code: 'HSS-018', item_name_ml: 'Book Test (Girls)',              participation_type: 'individual', category_codes: ['HSS']                       },
  { id: 'item-hss-019', item_code: 'HSS-019', item_name_ml: 'Story Writing (Girls)',          participation_type: 'individual', category_codes: ['HSS']                       },
  { id: 'item-hss-020', item_code: 'HSS-020', item_name_ml: 'Poetry Writing (Girls)',         participation_type: 'individual', category_codes: ['HSS']                       },

  // ── Junior (JR) — 21 items ──
  { id: 'item-jr-001', item_code: 'JR-001', item_name_ml: 'Literary Debate',               participation_type: 'individual', category_codes: ['JR']                       },
  { id: 'item-jr-002', item_code: 'JR-002', item_name_ml: 'Mappila Song',                  participation_type: 'individual', category_codes: ['JR'], duration_minutes: 5  },
  { id: 'item-jr-003', item_code: 'JR-003', item_name_ml: 'Speech – Malayalam',            participation_type: 'individual', category_codes: ['JR'], duration_minutes: 5  },
  { id: 'item-jr-004', item_code: 'JR-004', item_name_ml: 'Speech – Arabic',               participation_type: 'individual', category_codes: ['JR'], duration_minutes: 5  },
  { id: 'item-jr-005', item_code: 'JR-005', item_name_ml: 'Speech – English',              participation_type: 'individual', category_codes: ['JR'], duration_minutes: 5  },
  { id: 'item-jr-006', item_code: 'JR-006', item_name_ml: 'Poetry Writing',                participation_type: 'individual', category_codes: ['JR'], duration_minutes: 40 },
  { id: 'item-jr-007', item_code: 'JR-007', item_name_ml: 'Story Writing',                 participation_type: 'individual', category_codes: ['JR'], duration_minutes: 40 },
  { id: 'item-jr-008', item_code: 'JR-008', item_name_ml: 'Book Test',                     participation_type: 'individual', category_codes: ['JR'], duration_minutes: 15 },
  { id: 'item-jr-009', item_code: 'JR-009', item_name_ml: 'Essay – Malayalam',             participation_type: 'individual', category_codes: ['JR'], duration_minutes: 30 },
  { id: 'item-jr-010', item_code: 'JR-010', item_name_ml: 'Essay – Arabic',                participation_type: 'individual', category_codes: ['JR'], duration_minutes: 30 },
  { id: 'item-jr-011', item_code: 'JR-011', item_name_ml: 'Slogan Writing',                participation_type: 'individual', category_codes: ['JR'], duration_minutes: 40 },
  { id: 'item-jr-012', item_code: 'JR-012', item_name_ml: 'Madh Song Composition',         participation_type: 'individual', category_codes: ['JR'], duration_minutes: 40 },
  { id: 'item-jr-013', item_code: 'JR-013', item_name_ml: 'Quiz',                          participation_type: 'individual', category_codes: ['JR']                       },
  { id: 'item-jr-014', item_code: 'JR-014', item_name_ml: 'Translation – Arabic',          participation_type: 'individual', category_codes: ['JR'], duration_minutes: 40 },
  { id: 'item-jr-015', item_code: 'JR-015', item_name_ml: 'Arabic Calligraphy',            participation_type: 'individual', category_codes: ['JR'], duration_minutes: 60 },
  { id: 'item-jr-016', item_code: 'JR-016', item_name_ml: 'Social Text',                   participation_type: 'individual', category_codes: ['JR'], duration_minutes: 30 },
  { id: 'item-jr-017', item_code: 'JR-017', item_name_ml: 'Hadith Competition',            participation_type: 'individual', category_codes: ['JR']                       },
  { id: 'item-jr-018', item_code: 'JR-018', item_name_ml: 'AI Poetry Writing',             participation_type: 'individual', category_codes: ['JR'], duration_minutes: 30 },
  { id: 'item-jr-019', item_code: 'JR-019', item_name_ml: 'Reel Making',                   participation_type: 'individual', category_codes: ['JR']                       },
  { id: 'item-jr-020', item_code: 'JR-020', item_name_ml: 'Podcast',                       participation_type: 'individual', category_codes: ['JR']                       },
  { id: 'item-jr-021', item_code: 'JR-021', item_name_ml: 'Socio Synapse',                 participation_type: 'individual', category_codes: ['JR']                       },

  // ── Senior (SR) — 27 items ──
  { id: 'item-sr-001', item_code: 'SR-001', item_name_ml: 'Political Debate',              participation_type: 'individual', category_codes: ['SR']                       },
  { id: 'item-sr-002', item_code: 'SR-002', item_name_ml: 'Mappila Song',                  participation_type: 'individual', category_codes: ['SR'], duration_minutes: 5  },
  { id: 'item-sr-003', item_code: 'SR-003', item_name_ml: 'Hamd – Urdu',                   participation_type: 'individual', category_codes: ['SR'], duration_minutes: 5  },
  { id: 'item-sr-004', item_code: 'SR-004', item_name_ml: 'Poem Recitation – English',     participation_type: 'individual', category_codes: ['SR'], duration_minutes: 5  },
  { id: 'item-sr-005', item_code: 'SR-005', item_name_ml: 'Speech – Malayalam',            participation_type: 'individual', category_codes: ['SR'], duration_minutes: 5  },
  { id: 'item-sr-006', item_code: 'SR-006', item_name_ml: 'Speech – English',              participation_type: 'individual', category_codes: ['SR'], duration_minutes: 5  },
  { id: 'item-sr-007', item_code: 'SR-007', item_name_ml: 'Speech – Urdu',                 participation_type: 'individual', category_codes: ['SR'], duration_minutes: 5  },
  { id: 'item-sr-008', item_code: 'SR-008', item_name_ml: 'Musaara Alfiyya',               participation_type: 'individual', category_codes: ['SR']                       },
  { id: 'item-sr-009', item_code: 'SR-009', item_name_ml: 'Poetry Writing – Malayalam',    participation_type: 'individual', category_codes: ['SR'], duration_minutes: 40 },
  { id: 'item-sr-010', item_code: 'SR-010', item_name_ml: 'Poetry Writing – English',      participation_type: 'individual', category_codes: ['SR'], duration_minutes: 40 },
  { id: 'item-sr-011', item_code: 'SR-011', item_name_ml: 'Story Writing',                 participation_type: 'individual', category_codes: ['SR'], duration_minutes: 40 },
  { id: 'item-sr-012', item_code: 'SR-012', item_name_ml: 'Book Test',                     participation_type: 'individual', category_codes: ['SR'], duration_minutes: 15 },
  { id: 'item-sr-013', item_code: 'SR-013', item_name_ml: 'Essay – Malayalam',             participation_type: 'individual', category_codes: ['SR'], duration_minutes: 30 },
  { id: 'item-sr-014', item_code: 'SR-014', item_name_ml: 'Essay – English',               participation_type: 'individual', category_codes: ['SR'], duration_minutes: 30 },
  { id: 'item-sr-015', item_code: 'SR-015', item_name_ml: 'Essay – Urdu',                  participation_type: 'individual', category_codes: ['SR'], duration_minutes: 30 },
  { id: 'item-sr-016', item_code: 'SR-016', item_name_ml: 'Translation – English',         participation_type: 'individual', category_codes: ['SR'], duration_minutes: 40 },
  { id: 'item-sr-017', item_code: 'SR-017', item_name_ml: 'Madh Song Composition',         participation_type: 'individual', category_codes: ['SR'], duration_minutes: 40 },
  { id: 'item-sr-018', item_code: 'SR-018', item_name_ml: 'Slogan Writing',                participation_type: 'individual', category_codes: ['SR'], duration_minutes: 40 },
  { id: 'item-sr-019', item_code: 'SR-019', item_name_ml: 'Quiz',                          participation_type: 'individual', category_codes: ['SR']                       },
  { id: 'item-sr-020', item_code: 'SR-020', item_name_ml: 'Feature Writing',               participation_type: 'individual', category_codes: ['SR'], duration_minutes: 60 },
  { id: 'item-sr-021', item_code: 'SR-021', item_name_ml: 'Social Text',                   participation_type: 'individual', category_codes: ['SR'], duration_minutes: 30 },
  { id: 'item-sr-022', item_code: 'SR-022', item_name_ml: 'Poster Designing',              participation_type: 'individual', category_codes: ['SR'], duration_minutes: 60 },
  { id: 'item-sr-023', item_code: 'SR-023', item_name_ml: 'E-Poster',                      participation_type: 'individual', category_codes: ['SR'], duration_minutes: 60 },
  { id: 'item-sr-024', item_code: 'SR-024', item_name_ml: 'Digital Illustration',          participation_type: 'individual', category_codes: ['SR'], duration_minutes: 60 },
  { id: 'item-sr-025', item_code: 'SR-025', item_name_ml: 'Magazine Layout',               participation_type: 'individual', category_codes: ['SR'], duration_minutes: 120 },
  { id: 'item-sr-026', item_code: 'SR-026', item_name_ml: 'Digital Painting',              participation_type: 'individual', category_codes: ['SR'], duration_minutes: 60 },
  { id: 'item-sr-027', item_code: 'SR-027', item_name_ml: 'Podcast',                       participation_type: 'individual', category_codes: ['SR']                       },

  // ── General (GN) — 19 items ──
  { id: 'item-gn-001', item_code: 'GN-001', item_name_ml: 'Spot Magazine',                 participation_type: 'group',      category_codes: ['GN'], duration_minutes: 60 },
  { id: 'item-gn-002', item_code: 'GN-002', item_name_ml: 'Daf (Percussion)',              participation_type: 'group',      category_codes: ['GN'], duration_minutes: 10 },
  { id: 'item-gn-003', item_code: 'GN-003', item_name_ml: 'Arabana (Percussion)',           participation_type: 'group',      category_codes: ['GN'], duration_minutes: 10 },
  { id: 'item-gn-004', item_code: 'GN-004', item_name_ml: 'Group Song A',                  participation_type: 'group',      category_codes: ['GN'], duration_minutes: 5  },
  { id: 'item-gn-005', item_code: 'GN-005', item_name_ml: 'Group Song B',                  participation_type: 'group',      category_codes: ['GN'], duration_minutes: 5  },
  { id: 'item-gn-006', item_code: 'GN-006', item_name_ml: 'Mawlid Recitation',             participation_type: 'group',      category_codes: ['GN'], duration_minutes: 5  },
  { id: 'item-gn-007', item_code: 'GN-007', item_name_ml: 'Qasida Recitation',             participation_type: 'group',      category_codes: ['GN'], duration_minutes: 5  },
  { id: 'item-gn-008', item_code: 'GN-008', item_name_ml: 'Revolutionary Song',            participation_type: 'group',      category_codes: ['GN'], duration_minutes: 5  },
  { id: 'item-gn-009', item_code: 'GN-009', item_name_ml: 'Wall Writing',                  participation_type: 'group',      category_codes: ['GN'], duration_minutes: 60 },
  { id: 'item-gn-010', item_code: 'GN-010', item_name_ml: 'Mala Song',                     participation_type: 'group',      category_codes: ['GN'], duration_minutes: 5  },
  { id: 'item-gn-011', item_code: 'GN-011', item_name_ml: 'Risala Quiz',                   participation_type: 'group',      category_codes: ['GN']                       },
  { id: 'item-gn-012', item_code: 'GN-012', item_name_ml: 'Qawwali',                       participation_type: 'group',      category_codes: ['GN'], duration_minutes: 10 },
  { id: 'item-gn-013', item_code: 'GN-013', item_name_ml: 'Revolutionary Song Composition', participation_type: 'individual', category_codes: ['GN'], duration_minutes: 40 },
  { id: 'item-gn-014', item_code: 'GN-014', item_name_ml: 'Mappila Song Composition',       participation_type: 'individual', category_codes: ['GN'], duration_minutes: 40 },
  { id: 'item-gn-015', item_code: 'GN-015', item_name_ml: 'Social Story',                  participation_type: 'individual', category_codes: ['GN'], duration_minutes: 7  },
  { id: 'item-gn-016', item_code: 'GN-016', item_name_ml: 'Project',                       participation_type: 'group',      category_codes: ['GN']                       },
  { id: 'item-gn-017', item_code: 'GN-017', item_name_ml: 'Collage',                       participation_type: 'group',      category_codes: ['GN'], duration_minutes: 60 },
  { id: 'item-gn-018', item_code: 'GN-018', item_name_ml: 'Nasheed',                       participation_type: 'group',      category_codes: ['GN'], duration_minutes: 7  },
  { id: 'item-gn-019', item_code: 'GN-019', item_name_ml: 'Family Magazine',               participation_type: 'individual', category_codes: ['GN']                       },

  // ── Campus (CA) — 30 items ──
  { id: 'item-ca-001', item_code: 'CA-001', item_name_ml: 'Mappila Song',                  participation_type: 'individual', category_codes: ['CA'], duration_minutes: 5  },
  { id: 'item-ca-002', item_code: 'CA-002', item_name_ml: 'Madh Song',                     participation_type: 'individual', category_codes: ['CA'], duration_minutes: 5  },
  { id: 'item-ca-003', item_code: 'CA-003', item_name_ml: 'Speech – Malayalam',            participation_type: 'individual', category_codes: ['CA'], duration_minutes: 5  },
  { id: 'item-ca-004', item_code: 'CA-004', item_name_ml: 'Speech – English',              participation_type: 'individual', category_codes: ['CA'], duration_minutes: 5  },
  { id: 'item-ca-005', item_code: 'CA-005', item_name_ml: 'Essay – Malayalam',             participation_type: 'individual', category_codes: ['CA'], duration_minutes: 30 },
  { id: 'item-ca-006', item_code: 'CA-006', item_name_ml: 'Essay – English',               participation_type: 'individual', category_codes: ['CA'], duration_minutes: 30 },
  { id: 'item-ca-007', item_code: 'CA-007', item_name_ml: 'Story Writing – Malayalam',      participation_type: 'individual', category_codes: ['CA'], duration_minutes: 40 },
  { id: 'item-ca-008', item_code: 'CA-008', item_name_ml: 'Poetry Writing – Malayalam',     participation_type: 'individual', category_codes: ['CA'], duration_minutes: 40 },
  { id: 'item-ca-009', item_code: 'CA-009', item_name_ml: 'Poetry Writing – English',       participation_type: 'individual', category_codes: ['CA'], duration_minutes: 40 },
  { id: 'item-ca-010', item_code: 'CA-010', item_name_ml: 'Drawing – Pencil',              participation_type: 'individual', category_codes: ['CA'], duration_minutes: 60 },
  { id: 'item-ca-011', item_code: 'CA-011', item_name_ml: 'Drawing – Watercolour',         participation_type: 'individual', category_codes: ['CA'], duration_minutes: 60 },
  { id: 'item-ca-012', item_code: 'CA-012', item_name_ml: 'Quiz',                          participation_type: 'group',      category_codes: ['CA']                       },
  { id: 'item-ca-013', item_code: 'CA-013', item_name_ml: 'Book Test',                     participation_type: 'individual', category_codes: ['CA'], duration_minutes: 15 },
  { id: 'item-ca-014', item_code: 'CA-014', item_name_ml: 'E-Poster',                      participation_type: 'individual', category_codes: ['CA'], duration_minutes: 60 },
  { id: 'item-ca-015', item_code: 'CA-015', item_name_ml: 'Vlog',                          participation_type: 'individual', category_codes: ['CA'], duration_minutes: 7  },
  { id: 'item-ca-016', item_code: 'CA-016', item_name_ml: 'Top Comment',                   participation_type: 'individual', category_codes: ['CA']                       },
  { id: 'item-ca-017', item_code: 'CA-017', item_name_ml: 'Political Debate',              participation_type: 'group',      category_codes: ['CA']                       },
  { id: 'item-ca-018', item_code: 'CA-018', item_name_ml: 'Campus Magazine',               participation_type: 'individual', category_codes: ['CA']                       },
  { id: 'item-ca-019', item_code: 'CA-019', item_name_ml: 'DPR Presentation',              participation_type: 'individual', category_codes: ['CA'], duration_minutes: 20 },
  { id: 'item-ca-020', item_code: 'CA-020', item_name_ml: 'Capture the Flag',                participation_type: 'individual', category_codes: ['CA']                       },
  { id: 'item-ca-021', item_code: 'CA-021', item_name_ml: 'Language Pro',                  participation_type: 'individual', category_codes: ['CA']                       },
  { id: 'item-ca-022', item_code: 'CA-022', item_name_ml: 'Online Quiz',                   participation_type: 'individual', category_codes: ['CA']                       },
  { id: 'item-ca-023', item_code: 'CA-023', item_name_ml: 'AI Prompting',                  participation_type: 'individual', category_codes: ['CA'], duration_minutes: 30 },
  { id: 'item-ca-024', item_code: 'CA-024', item_name_ml: 'Ideathon',                      participation_type: 'individual', category_codes: ['CA']                       },
  { id: 'item-ca-025', item_code: 'CA-025', item_name_ml: 'Market Masters',                participation_type: 'individual', category_codes: ['CA']                       },
  { id: 'item-ca-026', item_code: 'CA-026', item_name_ml: 'Book Title',                    participation_type: 'individual', category_codes: ['CA']                       },
  { id: 'item-ca-027', item_code: 'CA-027', item_name_ml: 'Essay – Malayalam (Girls)',      participation_type: 'individual', category_codes: ['CA']                       },
  { id: 'item-ca-028', item_code: 'CA-028', item_name_ml: 'Essay – English (Girls)',        participation_type: 'individual', category_codes: ['CA']                       },
  { id: 'item-ca-029', item_code: 'CA-029', item_name_ml: 'Story Writing – Malayalam (Girls)', participation_type: 'individual', category_codes: ['CA']                  },
  { id: 'item-ca-030', item_code: 'CA-030', item_name_ml: 'Story Writing – English (Girls)',   participation_type: 'individual', category_codes: ['CA']                  },

];
